name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install
        run: |
          npm install
      - name: update papers
        run: |
          rm -f ./data/**/_Example.ttl
          npm run papers
      - name: build
        run: npm run build
